language: python
group: travis_latest
os: linux
dist: bionic

git:
  depth: 10

python:
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
 
cache:
  apt: true
  pip: true

before_install:
 - pip install -r requirements.txt

install:
 - cd $TRAVIS_BUILD_DIR
 - pip install .
