language: python
group: travis_latest
os: linux
dist: bionic

git:
  depth: 10

python:
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
 
cache:
  apt: true
  pip: true

before_install:
 - pip install -r requirements.txt
 - pip install pytest pytest-cov

script:
 - cd $TRAVIS_BUILD_DIR
 - export OMP_NUM_THREADS=1
 - export PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH
 - pytest -v --durations=0 --cov-config=./.coveragerc --cov=./pycosmosac --cov-report=xml --cov-report=term ./pycosmosac

after_success:
 - bash <(curl -s https://codecov.io/bash) -t "d755021d-0f71-44d8-9f22-3c6ebf29bbd2" -f "coverage.xml"
